# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
stages:
  - stage: RunAutomatedTests
    displayName: Run Automated Tests
    jobs:
      - job: RunAutomatedTests
        pool:
          name: Default
          # vmImage: windows-latest
        steps:
        - template: run-automated-tests.yml